/**
 * Centralized Mock Data Store for Pother Dake Mobile
 * Provides realistic test data for all application flows
 */

import { User, Driver, Passenger, Trip, Booking, Location } from '../types';

// Sample locations in Bangladesh (realistic for Pother Dake)
const LOCATIONS = {
  dhaka_center: { name: 'Dhaka City Center', latitude: 23.8103, longitude: 90.4125 },
  gulshan: { name: 'Gulshan', latitude: 23.7973, longitude: 90.4243 },
  dhanmondi: { name: 'Dhanmondi', latitude: 23.7479, longitude: 90.3667 },
  mirpur: { name: 'Mirpur', latitude: 23.8147, longitude: 90.3658 },
  airport: { name: 'Hazrat Shahjalal Airport', latitude: 23.8411, longitude: 90.4062 },
  uttara: { name: 'Uttara', latitude: 23.8763, longitude: 90.3659 },
  banani: { name: 'Banani', latitude: 23.8288, longitude: 90.4108 },
  baridhara: { name: 'Baridhara', latitude: 23.8074, longitude: 90.4378 },
  ramna: { name: 'Ramna Park', latitude: 23.7562, longitude: 90.4151 },
  bashundhara: { name: 'Bashundhara', latitude: 23.8012, longitude: 90.4465 },
} as const;

// Mock Users/Drivers
export const mockDrivers: Driver[] = [
  {
    id: 'd1',
    name: 'Ashraf Khan',
    email: 'ashraf.khan@potherdake.com',
    phone: '+8801712345678',
    avatar: '👨',
    role: 'DRIVER',
    rating: 4.9,
    completedRides: 847,
    joinedDate: '2022-03-15',
    vehicleType: 'Toyota Prius',
    vehicleColor: 'Silver',
    vehicleNumber: 'DH-23-4567',
    licenseNumber: 'LIC-123456',
    totalTrips: 847,
  },
  {
    id: 'd2',
    name: 'Md Rana',
    email: 'rana.driver@potherdake.com',
    phone: '+8801798765432',
    avatar: '👨',
    role: 'DRIVER',
    rating: 4.7,
    completedRides: 542,
    joinedDate: '2022-07-22',
    vehicleType: 'Hyundai i10',
    vehicleColor: 'Black',
    vehicleNumber: 'DH-24-1234',
    licenseNumber: 'LIC-789012',
    totalTrips: 542,
  },
  {
    id: 'd3',
    name: 'Fatima Begum',
    email: 'fatima.driver@potherdake.com',
    phone: '+8801856789012',
    avatar: '👩',
    role: 'DRIVER',
    rating: 4.8,
    completedRides: 623,
    joinedDate: '2022-05-10',
    vehicleType: 'Suzuki Swift',
    vehicleColor: 'Red',
    vehicleNumber: 'DH-25-5678',
    licenseNumber: 'LIC-345678',
    totalTrips: 623,
  },
  {
    id: 'd4',
    name: 'Karim Hassan',
    email: 'karim.driver@potherdake.com',
    phone: '+8801923456789',
    avatar: '👨',
    role: 'DRIVER',
    rating: 4.5,
    completedRides: 421,
    joinedDate: '2023-01-08',
    vehicleType: 'Toyota Noah',
    vehicleColor: 'White',
    vehicleNumber: 'DH-26-9012',
    licenseNumber: 'LIC-567890',
    totalTrips: 421,
  },
];

// Mock Users/Passengers
export const mockPassengers: Passenger[] = [
  {
    id: 'p1',
    name: 'Samir Ahmed',
    email: 'samir@example.com',
    phone: '+8801634567890',
    avatar: '👨',
    role: 'PASSENGER',
    rating: 4.6,
    totalBookings: 23,
    joinedDate: '2023-02-10',
    preferredPaymentMethod: 'CARD',
  },
  {
    id: 'p2',
    name: 'Nadia Hossain',
    email: 'nadia@example.com',
    phone: '+8801745678901',
    avatar: '👩',
    role: 'PASSENGER',
    rating: 4.8,
    totalBookings: 56,
    joinedDate: '2022-11-05',
    preferredPaymentMethod: 'CASH',
  },
  {
    id: 'p3',
    name: 'Tariq Mahmud',
    email: 'tariq@example.com',
    phone: '+8801856789012',
    avatar: '👨',
    role: 'PASSENGER',
    rating: 4.3,
    totalBookings: 12,
    joinedDate: '2023-05-20',
    preferredPaymentMethod: 'CARD',
  },
];

// Mock Admin
export const mockAdmin: User = {
  id: 'admin1',
  name: 'Admin Dashboard',
  email: 'admin@potherdake.com',
  phone: '+8801900000000',
  avatar: '👤',
  role: 'ADMIN',
  rating: 5.0,
};

// Mock Trips
export const mockTrips: Trip[] = [
  {
    id: 'trip1',
    driverId: 'd1',
    driver: mockDrivers[0],
    origin: LOCATIONS.dhaka_center,
    destination: LOCATIONS.airport,
    departureDate: '2026-08-16',
    departureTime: '08:00',
    estimatedArrivalTime: '09:15',
    totalSeats: 4,
    availableSeats: 2,
    pricePerSeat: 450,
    status: 'SCHEDULED',
    description: 'Comfortable journey to airport',
    vehicleType: 'Toyota Prius',
    createdAt: '2026-08-15T10:00:00Z',
    passengers: [
      {
        id: 'booking1',
        tripId: 'trip1',
        passengerId: 'p1',
        passenger: mockPassengers[0],
        seatsBooked: 2,
        status: 'CONFIRMED',
        bookingDate: '2026-08-15T11:00:00Z',
        paymentStatus: 'PAID',
      },
    ],
    preferences: {
      ac: true,
      music: true,
      luggage: true,
      pets: false,
      smoking: false,
      maxLuggageWeight: 15,
    },
  },
  {
    id: 'trip2',
    driverId: 'd2',
    driver: mockDrivers[1],
    origin: LOCATIONS.gulshan,
    destination: LOCATIONS.dhanmondi,
    departureDate: '2026-08-16',
    departureTime: '09:30',
    estimatedArrivalTime: '10:15',
    totalSeats: 4,
    availableSeats: 4,
    pricePerSeat: 200,
    status: 'SCHEDULED',
    description: 'Short ride through town',
    vehicleType: 'Hyundai i10',
    createdAt: '2026-08-15T09:45:00Z',
    passengers: [],
    preferences: {
      ac: false,
      music: false,
      luggage: true,
      pets: false,
      smoking: false,
    },
  },
  {
    id: 'trip3',
    driverId: 'd3',
    driver: mockDrivers[2],
    origin: LOCATIONS.mirpur,
    destination: LOCATIONS.banani,
    departureDate: '2026-08-16',
    departureTime: '14:00',
    estimatedArrivalTime: '15:30',
    totalSeats: 4,
    availableSeats: 0,
    pricePerSeat: 320,
    status: 'SCHEDULED',
    description: 'Full trip - no seats available',
    vehicleType: 'Suzuki Swift',
    createdAt: '2026-08-15T12:00:00Z',
    passengers: [
      {
        id: 'booking2',
        tripId: 'trip3',
        passengerId: 'p2',
        passenger: mockPassengers[1],
        seatsBooked: 2,
        status: 'CONFIRMED',
        bookingDate: '2026-08-15T12:30:00Z',
        paymentStatus: 'PAID',
      },
      {
        id: 'booking3',
        tripId: 'trip3',
        passengerId: 'p3',
        passenger: mockPassengers[2],
        seatsBooked: 2,
        status: 'CONFIRMED',
        bookingDate: '2026-08-15T12:45:00Z',
        paymentStatus: 'PENDING',
      },
    ],
    preferences: {
      ac: true,
      music: true,
      luggage: true,
      pets: false,
      smoking: false,
      womenOnly: false,
    },
  },
  {
    id: 'trip4',
    driverId: 'd1',
    driver: mockDrivers[0],
    origin: LOCATIONS.uttara,
    destination: LOCATIONS.gulshan,
    departureDate: '2026-08-16',
    departureTime: '11:00',
    estimatedArrivalTime: '12:00',
    totalSeats: 4,
    availableSeats: 3,
    pricePerSeat: 250,
    status: 'SCHEDULED',
    description: 'Morning ride from Uttara',
    vehicleType: 'Toyota Prius',
    createdAt: '2026-08-15T08:30:00Z',
    passengers: [
      {
        id: 'booking4',
        tripId: 'trip4',
        passengerId: 'p1',
        passenger: mockPassengers[0],
        seatsBooked: 1,
        status: 'CONFIRMED',
        bookingDate: '2026-08-15T09:00:00Z',
        paymentStatus: 'PAID',
      },
    ],
    preferences: {
      ac: true,
      music: false,
      luggage: false,
      pets: false,
      smoking: false,
    },
  },
  {
    id: 'trip5',
    driverId: 'd4',
    driver: mockDrivers[3],
    origin: LOCATIONS.bashundhara,
    destination: LOCATIONS.dhaka_center,
    departureDate: '2026-08-17',
    departureTime: '07:00',
    estimatedArrivalTime: '08:30',
    totalSeats: 7,
    availableSeats: 5,
    pricePerSeat: 300,
    status: 'SCHEDULED',
    description: 'Early morning trip',
    vehicleType: 'Toyota Noah',
    createdAt: '2026-08-15T07:00:00Z',
    passengers: [
      {
        id: 'booking5',
        tripId: 'trip5',
        passengerId: 'p2',
        passenger: mockPassengers[1],
        seatsBooked: 2,
        status: 'CONFIRMED',
        bookingDate: '2026-08-15T07:30:00Z',
        paymentStatus: 'PAID',
      },
    ],
    preferences: {
      ac: true,
      music: true,
      luggage: true,
      pets: false,
      smoking: false,
    },
  },
  {
    id: 'trip6',
    driverId: 'd2',
    driver: mockDrivers[1],
    origin: LOCATIONS.ramna,
    destination: LOCATIONS.baridhara,
    departureDate: '2026-08-16',
    departureTime: '16:00',
    estimatedArrivalTime: '17:00',
    totalSeats: 4,
    availableSeats: 2,
    pricePerSeat: 280,
    status: 'SCHEDULED',
    description: 'Evening ride',
    vehicleType: 'Hyundai i10',
    createdAt: '2026-08-15T14:00:00Z',
    passengers: [
      {
        id: 'booking6',
        tripId: 'trip6',
        passengerId: 'p3',
        passenger: mockPassengers[2],
        seatsBooked: 2,
        status: 'PENDING',
        bookingDate: '2026-08-15T14:30:00Z',
        paymentStatus: 'PENDING',
      },
    ],
    preferences: {
      ac: true,
      music: false,
      luggage: true,
      pets: false,
      smoking: false,
    },
  },
  {
    id: 'trip7',
    driverId: 'd3',
    driver: mockDrivers[2],
    origin: LOCATIONS.airport,
    destination: LOCATIONS.dhaka_center,
    departureDate: '2026-08-18',
    departureTime: '10:00',
    estimatedArrivalTime: '11:30',
    totalSeats: 4,
    availableSeats: 4,
    pricePerSeat: 450,
    status: 'SCHEDULED',
    description: 'Airport to city',
    vehicleType: 'Suzuki Swift',
    createdAt: '2026-08-15T06:00:00Z',
    passengers: [],
    preferences: {
      ac: true,
      music: true,
      luggage: true,
      pets: false,
      smoking: false,
    },
  },
];

// Mock dashboard stats
export const mockStats = {
  totalRides: 5432,
  todayRides: 18,
  revenueToday: '৳ 12,450',
  activeUsers: 2341,
};

// Mock completed trips (for history)
export const mockCompletedTrips: Trip[] = [
  {
    id: 'trip-completed-1',
    driverId: 'd1',
    driver: mockDrivers[0],
    origin: LOCATIONS.dhaka_center,
    destination: LOCATIONS.gulshan,
    departureDate: '2026-08-14',
    departureTime: '09:00',
    estimatedArrivalTime: '10:00',
    totalSeats: 4,
    availableSeats: 0,
    pricePerSeat: 200,
    status: 'COMPLETED',
    description: 'Completed trip',
    vehicleType: 'Toyota Prius',
    createdAt: '2026-08-14T08:00:00Z',
    passengers: [
      {
        id: 'booking-c1',
        tripId: 'trip-completed-1',
        passengerId: 'p1',
        passenger: mockPassengers[0],
        seatsBooked: 2,
        status: 'COMPLETED',
        bookingDate: '2026-08-14T08:15:00Z',
        paymentStatus: 'PAID',
      },
      {
        id: 'booking-c2',
        tripId: 'trip-completed-1',
        passengerId: 'p2',
        passenger: mockPassengers[1],
        seatsBooked: 2,
        status: 'COMPLETED',
        bookingDate: '2026-08-14T08:30:00Z',
        paymentStatus: 'PAID',
      },
    ],
    preferences: {
      ac: true,
      music: true,
      luggage: true,
    },
  },
];

// Export all mock data
export const mockDataStore = {
  drivers: mockDrivers,
  passengers: mockPassengers,
  admin: mockAdmin,
  trips: mockTrips,
  completedTrips: mockCompletedTrips,
  stats: mockStats,
  locations: LOCATIONS,
};

export default mockDataStore;
